In [2]:
import os
import numpy as np
import pandas as pd
import pymzn
import time

In [46]:
classes = 24
rooms = 4
sections = 4
teachers = 12

### Randomly initialization

In [23]:
tList = np.random.randint(1,teachers+1,size=(classes))
sList = np.random.randint(1,sections+1,size=(classes))
hList = np.random.randint(3,4,size=(classes))

tList[0] = 1
j=0
for i in range(0,classes):
    if i%sections==0:
#         print("i ran",tList[i])
        j=j+1
        for s in range(0,sections):
            tList[i+s] = j
            sList[i+s] = s+1

classDetails = np.array([tList, sList, hList])
classDetails = classDetails.T
classDetails2 = classDetails
# print(classDetails)
# print(classDetails.shape[0])
print(classDetails)
classes = classDetails.shape[0]
classDetails = classDetails.tolist()
classDetails2 = classDetails[:]

[[1 1 3]
 [1 2 3]
 [2 1 3]
 [2 2 3]
 [3 1 3]
 [3 2 3]
 [4 1 3]
 [4 2 3]
 [5 1 3]
 [5 2 3]
 [6 1 3]
 [6 2 3]]


In [24]:
for item in classDetails2:
    classDetails.append([item[0]+6,item[1]+2,item[2]])
classDetails

[[1, 1, 3],
 [1, 2, 3],
 [2, 1, 3],
 [2, 2, 3],
 [3, 1, 3],
 [3, 2, 3],
 [4, 1, 3],
 [4, 2, 3],
 [5, 1, 3],
 [5, 2, 3],
 [6, 1, 3],
 [6, 2, 3],
 [7, 3, 3],
 [7, 4, 3],
 [8, 3, 3],
 [8, 4, 3],
 [9, 3, 3],
 [9, 4, 3],
 [10, 3, 3],
 [10, 4, 3],
 [11, 3, 3],
 [11, 4, 3],
 [12, 3, 3],
 [12, 4, 3]]

In [26]:
tBusy = np.zeros((teachers,5,6))
for i in range(0,6):
    tBusy[0,0,i] = 1
    tBusy[0,1,i] = 1
    tBusy[1,0,i] = 1
# print(tBusy.astype(int))
teacherBusy = tBusy.astype(int).tolist()

In [47]:
newDict = {}
newDict["classes"] = classes
newDict["rooms"] = rooms
newDict["sections"] = sections
newDict["teachers"] = teachers
newDict["classDetails"] = classDetails
newDict["teacherBusy"] = teacherBusy

pymzn.dict2dzn(newDict)
newDict

{'classes': 24,
 'rooms': 4,
 'sections': 4,
 'teachers': 12,
 'classDetails': [[1, 1, 3],
  [1, 2, 3],
  [2, 1, 3],
  [2, 2, 3],
  [3, 1, 3],
  [3, 2, 3],
  [4, 1, 3],
  [4, 2, 3],
  [5, 1, 3],
  [5, 2, 3],
  [6, 1, 3],
  [6, 2, 3],
  [7, 3, 3],
  [7, 4, 3],
  [8, 3, 3],
  [8, 4, 3],
  [9, 3, 3],
  [9, 4, 3],
  [10, 3, 3],
  [10, 4, 3],
  [11, 3, 3],
  [11, 4, 3],
  [12, 3, 3],
  [12, 4, 3]],
 'teacherBusy': [[[1, 1, 1, 1, 1, 1],
   [1, 1, 1, 1, 1, 1],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0]],
  [[1, 1, 1, 1, 1, 1],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0]],
  [[0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0]],
  [[0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0]],
  [[0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0],
   [0, 0, 0, 0, 0, 0]],
  [[0, 0

### Minizinc Model

In [48]:
start = time.time()
newData = pymzn.minizinc(mzn = "master.mzn", data = newDict, solver = pymzn.chuffed)
end = time.time()
print(end-start)

1.4357593059539795


In [49]:
# teacherRoutine = newData[0]["teacherRoutine"]
# sectionRoutine = newData[0]["sectionRoutine"]
# roomRoutine = newData[0]["roomRoutine"]
if len(newData)>0:
    teacherRoutine = newData[0]["teacherRoutine"]
    sectionRoutine = newData[0]["sectionRoutine"]
    roomRoutine = newData[0]["roomRoutine"]
else:
    print("error")

### Print Output

In [50]:
teacherRoutine

[[[0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0],
  [2, 24, 9, 12, 6, 1],
  [24, 18, 1, 2, 24, 24],
  [24, 1, 24, 24, 24, 2]],
 [[0, 0, 0, 0, 0, 0],
  [24, 23, 3, 24, 4, 11],
  [24, 24, 24, 24, 24, 4],
  [24, 0, 24, 3, 19, 21],
  [24, 24, 20, 4, 2, 3]],
 [[24, 17, 21, 6, 5, 24],
  [24, 3, 24, 9, 24, 17],
  [24, 19, 15, 6, 16, 3],
  [24, 12, 24, 24, 5, 20],
  [20, 24, 5, 24, 6, 24]],
 [[24, 24, 14, 24, 8, 24],
  [7, 21, 23, 24, 24, 24],
  [24, 22, 8, 24, 24, 24],
  [24, 7, 23, 24, 24, 1],
  [8, 14, 13, 7, 24, 18]],
 [[24, 9, 0, 24, 24, 24],
  [24, 24, 24, 9, 24, 3],
  [7, 24, 7, 24, 10, 7],
  [23, 13, 10, 7, 2, 9],
  [16, 18, 10, 22, 16, 14]],
 [[24, 14, 20, 1, 13, 11],
  [17, 12, 24, 24, 24, 24],
  [24, 12, 24, 24, 11, 24],
  [11, 24, 24, 24, 24, 12],
  [24, 24, 24, 24, 24, 0]],
 [[24, 24, 24, 14, 24, 24],
  [14, 24, 8, 24, 24, 24],
  [24, 24, 24, 13, 14, 24],
  [18, 24, 20, 24, 13, 16],
  [13, 24, 24, 24, 24, 24]],
 [[20, 16, 24, 22, 15, 22],
  [23, 24, 18, 24, 24, 15],
  [24, 24, 22, 22, 0

In [51]:
print(np.array(sectionRoutine))

[[[24  9 24 24  5 11]
  [ 7 24  3  9 24 23]
  [24 24 24 24 11  1]
  [11  7  1  3  5  9]
  [24  1  5  7 23  3]]

 [[24 24  8  6  8 24]
  [24 12 24 24  4 24]
  [ 2 12  8  6 10  4]
  [24 24 10  2 24 12]
  [ 8 24 10  4  6  2]]

 [[17 21 19 20 15 23]
  [24 24 19 17 21 15]
  [19 24 21 13 16 20]
  [17 24 15 23 13 21]
  [13 23 24 24 23 23]]

 [[24 16 24 14 18 20]
  [14 24 22 24 20 18]
  [22 24 22 24 14 20]
  [24 24 21 22 18 16]
  [24 24 24 16 24 24]]]


In [52]:
print(np.array(teacherRoutine))

[[[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 2 24  9 12  6  1]
  [24 18  1  2 24 24]
  [24  1 24 24 24  2]]

 [[ 0  0  0  0  0  0]
  [24 23  3 24  4 11]
  [24 24 24 24 24  4]
  [24  0 24  3 19 21]
  [24 24 20  4  2  3]]

 [[24 17 21  6  5 24]
  [24  3 24  9 24 17]
  [24 19 15  6 16  3]
  [24 12 24 24  5 20]
  [20 24  5 24  6 24]]

 [[24 24 14 24  8 24]
  [ 7 21 23 24 24 24]
  [24 22  8 24 24 24]
  [24  7 23 24 24  1]
  [ 8 14 13  7 24 18]]

 [[24  9  0 24 24 24]
  [24 24 24  9 24  3]
  [ 7 24  7 24 10  7]
  [23 13 10  7  2  9]
  [16 18 10 22 16 14]]

 [[24 14 20  1 13 11]
  [17 12 24 24 24 24]
  [24 12 24 24 11 24]
  [11 24 24 24 24 12]
  [24 24 24 24 24  0]]

 [[24 24 24 14 24 24]
  [14 24  8 24 24 24]
  [24 24 24 13 14 24]
  [18 24 20 24 13 16]
  [13 24 24 24 24 24]]

 [[20 16 24 22 15 22]
  [23 24 18 24 24 15]
  [24 24 22 22  0 24]
  [23 23 15 24 24 16]
  [11  8  9 16  9 24]]

 [[17 23 24 24 18 24]
  [24 24 24 17 24 18]
  [24 24 22 22 24 24]
  [17  4 24 10 18 24]
  [24 12 24  7 2

In [ ]:
# np.array(teacherRoutine).shape